/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'islamic-green': {
          50: '#f0f7f3',
          100: '#d4e6d9',
          200: '#a8cdb4',
          300: '#73aa86',
          400: '#3d8059',
          500: '#1B4332',
          600: '#163828',
          700: '#112d1f',
          800: '#0d2217',
          900: '#0F2419',
          DEFAULT: '#1B4332',
        },
        'islamic-gold': {
          50: '#fdf9ed',
          100: '#f9efc6',
          200: '#f3db8e',
          300: '#ecc14e',
          400: '#C9A84C',
          500: '#b8922e',
          600: '#9a7423',
          700: '#7a5a1c',
          800: '#5c4215',
          900: '#3d2c0d',
          DEFAULT: '#C9A84C',
        },
        'islamic-cream': {
          50: '#fefcf9',
          100: '#F8F4ED',
          200: '#f0e8d8',
          300: '#e4d4b8',
          400: '#d4b990',
          DEFAULT: '#F8F4ED',
        },
        'islamic-brown': {
          DEFAULT: '#2D1B0E',
          light: '#4a3020',
          dark: '#1a0f07',
        },
        'islamic-border': '#E8DDD0',
        'islamic-accent': '#D4E6D9',
        'islamic-dark': '#0F2419',
        madhab: {
          hanafi: '#3B82F6',
          'hanafi-light': '#EFF6FF',
          maliki: '#0D9488',
          'maliki-light': '#F0FDFA',
          shafii: '#10B981',
          'shafi-light': '#ECFDF5',
          hanbali: '#D97706',
          'hanbali-light': '#FFFBEB',
        },
      },
      fontFamily: {
        arabic: ['Cairo', 'sans-serif'],
        'arabic-heading': ['"Scheherazade New"', 'serif'],
        english: ['Inter', 'sans-serif'],
        sans: ['Cairo', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'arabic-sm': ['0.9rem', { lineHeight: '1.8' }],
        'arabic-base': ['1rem', { lineHeight: '2' }],
        'arabic-lg': ['1.1rem', { lineHeight: '2' }],
        'arabic-xl': ['1.3rem', { lineHeight: '1.8' }],
        'arabic-2xl': ['1.6rem', { lineHeight: '1.6' }],
        'arabic-3xl': ['2rem', { lineHeight: '1.5' }],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
        72: '18rem',
        84: '21rem',
        96: '24rem',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      boxShadow: {
        'warm-sm': '0 1px 3px rgba(45, 27, 14, 0.08), 0 1px 2px rgba(45, 27, 14, 0.06)',
        warm: '0 4px 6px rgba(45, 27, 14, 0.07), 0 2px 4px rgba(45, 27, 14, 0.06)',
        'warm-md': '0 10px 25px rgba(45, 27, 14, 0.1), 0 4px 10px rgba(45, 27, 14, 0.06)',
        'warm-lg': '0 20px 40px rgba(45, 27, 14, 0.12), 0 8px 20px rgba(45, 27, 14, 0.08)',
        'warm-xl': '0 30px 60px rgba(45, 27, 14, 0.15), 0 12px 30px rgba(45, 27, 14, 0.10)',
        islamic: '0 4px 20px rgba(27, 67, 50, 0.15), 0 2px 8px rgba(27, 67, 50, 0.10)',
        gold: '0 4px 20px rgba(201, 168, 76, 0.2), 0 2px 8px rgba(201, 168, 76, 0.12)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'slide-in-right': 'slideInRight 0.3s ease-out forwards',
        'slide-in-left': 'slideInLeft 0.3s ease-out forwards',
        'spin-slow': 'spin 8s linear infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'bounce-soft': 'bounceSoft 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      backgroundImage: {
        'islamic-gradient': 'linear-gradient(135deg, #1B4332 0%, #0F2419 100%)',
        'gold-gradient': 'linear-gradient(135deg, #C9A84C 0%, #b8922e 100%)',
        'cream-gradient': 'linear-gradient(180deg, #F8F4ED 0%, #f0e8d8 100%)',
        'shimmer-gradient': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 50%, transparent 100%)',
      },
      typography: (theme) => ({
        arabic: {
          css: {
            '--tw-prose-body': theme('colors.islamic-brown.DEFAULT'),
            '--tw-prose-headings': theme('colors.islamic-green.DEFAULT'),
            '--tw-prose-links': theme('colors.islamic-gold.DEFAULT'),
            '--tw-prose-bold': theme('colors.islamic-brown.DEFAULT'),
            '--tw-prose-quotes': theme('colors.islamic-green.DEFAULT'),
            '--tw-prose-quote-borders': theme('colors.islamic-gold.DEFAULT'),
            fontFamily: theme('fontFamily.arabic'),
            lineHeight: '2',
            fontSize: '1rem',
            maxWidth: 'none',
            'h1, h2, h3, h4': {
              fontFamily: theme('fontFamily.arabic-heading'),
            },
            blockquote: {
              borderRightWidth: '4px',
              borderLeftWidth: '0',
              borderColor: theme('colors.islamic-gold.DEFAULT'),
              paddingRight: '1.25rem',
              paddingLeft: '0',
              fontStyle: 'normal',
              color: theme('colors.islamic-brown.DEFAULT'),
              backgroundColor: theme('colors.islamic-cream.DEFAULT'),
              borderRadius: '0.5rem',
              padding: '1rem 1.25rem',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
